### ISSUE TITLE
Add info to Chrome Web Store that the extension is open source

### ISSUE THREAD

**Issue by Nowaker** [jeremyschlatter/always-smile#1]
Please mention it's an open source extension and provide a link to GitHub in https://chrome.google.com/webstore/detail/always-smile/fpaapignoneonaghhkoddkghglbppdmg?hl=en. This will help people make a better decision as to which plugin to install. Greetings from Geekdom.

**Comment by jeremyschlatter** [comment]
A little late, but this is now done. 🙂

Thanks for the suggestion!

**Comment by Nowaker** [comment]
Never too late, I've been using this extension for 4 years now!
