### ISSUE TITLE
Open Source Update?

### ISSUE THREAD

**Issue by bmitchinson** [jeremyschlatter/always-smile#4]
[Store](https://chrome.google.com/webstore/detail/always-smile/fpaapignoneonaghhkoddkghglbppdmg?hl=en) says that the extension was updated a month ago, but the master branch hasn't seen activity in 6 years?

![image](https://user-images.githubusercontent.com/33632286/72675346-ccb93400-3a47-11ea-8050-27374b78d805.png)

Thanks for your work on this.

**Comment by jeremyschlatter** [comment]
That update was just changing the description in the store to add a link to this repo, per #1.

The content of the extension hasn't changed in 6 years.
